### ISSUE TITLE
New feature : by default the validator should stop at "isRequired" tests

### ISSUE THREAD

**Issue by fdelaneau** [Rhinostone/gina#6]
There is no simply point at showing the user all the other kind of errors that are linked to the fact that he didn’t fill this field. In fact there is no use to go further than this test if the field is empty.

This should be a global default setting that can be overridden, locally or globally.

**Comment by Martin-Luther** [comment]
Agreed, this will be changed soon.

**Comment by Martin-Luther** [comment]
Fixed in the new version
